# /docker/Dockerfile.publish

# Multi-stage build for production
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production runtime
FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.output/public ./public
COPY --from=builder /app/.output/server ./server
EXPOSE 3000
CMD ["node", "./server/index.mjs"]
