# /docker/Dockerfile.init

FROM node:22-alpine
WORKDIR /app
COPY init.sh .
RUN apk update && \
    apk add dos2unix git && \
    dos2unix init.sh && \
    chmod +x init.sh
ENTRYPOINT ["/bin/sh", "init.sh"]
